### ISSUE TITLE
erroneuos readout of TE from twix header  

### ISSUE THREAD

**Issue by amadeuskanaan** [CIC-methods/FID-A#1]
referring to siemens twix files acquired on VB-17.... Drift corrected files contain wrong TE. Should be a simple fix i would assme..

**Comment by gdevenyi** [comment]
Can you provide an example file and specify the "expected" output so we can test?

**Comment by jamienear** [comment]
I just uploaded a fix to this problem.  The TE and TR are now included as fields in the FID-A data structure format, and this information is now used by the processing pipelines (run_pressproc.m, run_specialproc.m) to specify the correct TE in the processed data files for LCModel analysis.  Thanks, Ahmad, for pointing out this problem!!!  -Jamie
