### ISSUE TITLE
Posting my 3 Questions wrt using FID-A to generate LCModel basis sets to Jamie and his response for every to see.

### ISSUE THREAD

**Issue by pom4pom** [CIC-methods/FID-A#3]
Hi Jamie,

I am checking to see if I can use FID-A to generate basis set for LCModel and have some questions for you.

1). Can you share metabolites spin systems for all metabolites, if not I guess I probably need guide line on the format of spin system.

The spin systems are stored in /FID-A-master/simulationTools/metabolites/

To load a specific metabolite such as Glutamate, for example, simply type 

load Glu;

at the command prompt.  To load all metabolites, type

load spinSystems;

2). File called 'maualForSimulationTools.txt is empty, is this intentional, if not can 
you please send to correct file.

‘manualForSimulationTools.txt’ is not supposed to be in the repository.  It appears there by mistake.  I will now remove it.  The actual manual information for the simulation toolkit is contained within the full manual, which I attached in my previous email.  

3). Under metabolites directory, which pulse sequence used to generate and
what is the TE used. GE, Siemens or Philips pulse timing and RF pulses?

The only things stored in the ‘metabolites’ directory are the spin system definitions (chemical shifts and couplings) for each metabolite.  To generate spectra from these, you need to run a simulation command.  For example, to run an ideal 3T PRESS simulation for glutamate with 2048 points, a spectral width of 2000Hz, a linewidth of 2 Hz and a TE of 30ms (TE1=10, TE2=20), you can use the following commands:

load Glu;
out=sim_press(2048,2000,2,3,sysGlu,0.01,0.03);
op_plotspec(out);

To run a simulation with specific RF pulse waveforms is slightly more complicated, but you can get an idea how to do this by looking at the script ‘run_simMegaPressShaped.m’.

I hope this helps!  Let me know if you have more questions!!

Jamie

**Comment by jamienear** [comment]
Thanks for your questions Pom.  Just re-posting my responses here for all to see:

1)  The spin systems are stored in /FID-A-master/simulationTools/metabolites/
To load a specific metabolite such as Glutamate, for example, simply type

`load Glu;`

at the command prompt. To load all metabolites, type

`load spinSystems;`



2)  'manualForSimulationTools.txt’ is not supposed to be in the repository. It appears there by mistake. I will now remove it. The actual manual information for the simulation toolkit is contained within the full manual, which I attached in my previous email.


3)  The only things stored in the ‘metabolites’ directory are the spin system definitions (chemical shifts and couplings) for each metabolite. To generate spectra from these, you need to run a simulation command. For example, to run an ideal 3T PRESS simulation for glutamate with 2048 points, a spectral width of 2000Hz, a linewidth of 2 Hz and a TE of 30ms (TE1=10, TE2=20), you can use the following commands:

`load Glu;`
`out=sim_press(2048,2000,2,3,sysGlu,0.01,0.03);`
`op_plotspec(out);`

To run a simulation with specific RF pulse waveforms is slightly more complicated, but you can get an idea how to do this by looking at the script ‘run_simMegaPressShaped.m’.

I hope this helps! Let me know if you have more questions!!

Jamie
