### ISSUE TITLE
Problem with PRESS simulation

### ISSUE THREAD

**Issue by rgabr** [CIC-methods/FID-A#34]
Hi,
First, thanks for the great work with FID-A. 
I was experimenting with FID-A, and was getting unexpected spectra when simulating PRESS. Debugging the problem led me to looking into sim_press() line 39:  d=sim_evolve(d,H,tau1/2); 
It appears that "tau1/2" should be "tau1/2000". After fixing this, my simulations appear to work fine now.
Please advise. 

Thank you,
Refaat Gabr

**Comment by jamienear** [comment]
Hi Refaat, 
I have now fixed this error.  Thanks very much for spotting it and letting me know!
Best wishes, 
Jamie
